[package]
name = "antoinelaborderiedotcom"
version = "0.1.0"
edition = "2021"

[dependencies]
axum = "0.8"
tokio = { version = "1", features = ["full"] }
askama = "0.13"
tower = "0.5"
tower-http = { version = "0.6", features = ["fs"] }
